import type { PublicationItemRow } from '@/types/content'

export const COMMENTARIES_SEED: PublicationItemRow[] = [
  {
    slug: `2026-remembering-karl-weick-asq-insights-july-2026`,
    year: `2026`,
    bodyHtml: `Remembering Karl Weick, ASQ Insights (July, 2026)`,
    links: [{ label: `Link`, href: `https://asqjournal.substack.com/p/remembering-karl-weick` }],
  },
  {
    slug: `2025-remembering-ikujiro-nonaka-our-valued-colleague-and-friend`,
    year: `2025`,
    bodyHtml: `Remembering Ikujiro Nonaka, our valued colleague and friend, Berkeley Haas Newsroom (18 March 2025)`,
    links: [{ label: `Link`, href: `https://newsroom.haas.berkeley.edu/remembering-ikujiro-nonaka-our-valued-colleague-and-friend/` }],
  },
  {
    slug: `2025-eh-canada-ton-bras-saitil-porter-la-paix-les-affaires-1`,
    year: `2025`,
    bodyHtml: `Eh Canada, ton bras sait-il porter la paix?, Les Affaires (1 April 2025)`,
    links: [{ label: `Link`, href: `https://www.lesaffaires.com/secteurs/politique/lettre-dhenry-mintzberg-eh-canada-ton-bras-sait-il-porter-la-paix/` }],
  },
  {
    slug: `2025-the-managers-job-50-years-later-harvard-business-review`,
    year: `2025`,
    bodyHtml: `“The Manager’s Job”, 50 Years Later, Harvard Business Review (19 March 2025)`,
    links: [{ label: `Link`, href: `https://hbr.org/2025/03/the-managers-job-50-years-later` }],
  },
  {
    slug: `2025-these-changes-to-our-national-anthems-are-frankly-overdue`,
    year: `2025`,
    bodyHtml: `These changes to our national anthems are, frankly, overdue, Toronto Star (28 June 2025)`,
    links: [{ label: `Link`, href: `https://www.thestar.com/opinion/contributors/these-changes-to-our-national-anthems-are-frankly-overdue/article_80949c31-5d45-46de-88f3-b3b30aa44eba.html` }],
  },
  {
    slug: `2025-instead-of-waiting-for-a-canadian-team-to-win-the-stanley-cu`,
    year: `2025`,
    bodyHtml: `Instead of waiting for a Canadian team to win the Stanley Cup, Canada should launch its own domestic hockey league, The Globe and Mail (3 October 2025)`,
    links: [{ label: `Link`, href: `https://www.theglobeandmail.com/opinion/article-nhl-stanley-cup-canada-domestic-hockey-league/` }],
  },
  {
    slug: `2023-to-understand-organizations-watch-sports-the-chief-executi`,
    year: `2023`,
    bodyHtml: `To Understand Organizations, Watch Sports, The Chief Executive (27 Feb 2023)`,
    links: [{ label: `Link`, href: `https://chiefexecutive.net/to-understand-organizations-watch-sports/` }],
  },
  {
    slug: `2023-what-is-dumbing-us-down-ceoworld-3-march-2023`,
    year: `2023`,
    bodyHtml: `What Is Dumbing Us Down?, CEOWorld (3 March 2023)`,
    links: [{ label: `Link`, href: `https://ceoworld.biz/2023/03/03/what-is-dumbing-us-down/` }],
  },
  {
    slug: `2023-decision-making-is-not-what-you-think-leadership-now-13-ma`,
    year: `2023`,
    bodyHtml: `Decision Making is Not What You Think, Leadership Now (13 March 2023)`,
    links: [{ label: `Link`, href: `https://www.leadershipnow.com/leadingblog/2023/03/todays_organizations_are_outwa.html` }],
  },
  {
    slug: `2023-the-inescapable-conundrums-of-managing-thought-leaders-03`,
    year: `2023`,
    bodyHtml: `The Inescapable Conundrums of Managing, Thought Leaders (03 April 2023)`,
    links: [{ label: `Link`, href: `https://www.qualitydigest.com/inside/management-article/inescapable-conundrums-managing-042623.html` }],
  },
  {
    slug: `2023-culture-and-conflict-porchlight-book-15-february-2023`,
    year: `2023`,
    bodyHtml: `Culture and Conflict, Porchlight Book (15 February 2023)`,
    links: [{ label: `Link`, href: `https://www.porchlightbooks.com/blog/changethis/2023/understanding-organizations` }],
  },
  {
    slug: `2023-rorganiser-les-cerveaux-pour-de-meilleurs-soins-de-sant-l`,
    year: `2023`,
    bodyHtml: `Réorganiser Les Cerveaux pour de Meilleurs Soins de Santé, La Presse (19 June 2023)`,
    links: [{ label: `Link`, href: `https://www.lapresse.ca/debats/opinions/2023-06-19/reorganiser-les-cerveaux-pour-de-meilleurs-soins-de-sante.php` }],
  },
  {
    slug: `2023-pourquoi-monsieur-legault-pour-quoi-la-presse-18-decemb`,
    year: `2023`,
    bodyHtml: `Pourquoi, Monsieur Legault? Pour quoi?, La Presse (18 December 2023)`,
    links: [{ label: `Link`, href: `https://www.lapresse.ca/affaires/2023-12-18/forum-des-affaires/pourquoi-monsieur-legault-pour-quoi.php` }],
  },
  {
    slug: `2022-our-groups-of-global-superpowers-need-a-balancing-force-for`,
    year: `2022`,
    bodyHtml: `Our Groups of Global Superpowers Need a Balancing Force for Democracy, The Hill (13 March 2022)`,
    links: [{ label: `Link`, href: `https://thehill.com/opinion/international/598580-our-groups-of-global-superpowers-need-a-balancing-force-for-democracy/` }],
  },
  {
    slug: `2017-must-we-tolerate-this-era-of-political-bullies-february-27`,
    year: `2017`,
    bodyHtml: `Must We Tolerate this Era of Political Bullies? (February 27, 2017), The Globe and Mail`,
    links: [],
  },
  {
    slug: `2017-comprendre-le-monde-audela-de-donald-trump-march-24-2017`,
    year: `2017`,
    bodyHtml: `Comprendre Le Monde au-dela de Donald Trump (March 24, 2017), Huffington Post`,
    links: [],
  },
  {
    slug: `2016-saving-the-planet-from-governments-and-markets-the-world-po`,
    year: `2016`,
    bodyHtml: `Saving the Planet From Governments and Markets, The World Post (9 May 2016)`,
    links: [{ label: `Link`, href: `http://www.huffingtonpost.com/henry-mintzberg/saving-the-planet-from-go_b_9856304.html` }],
  },
  {
    slug: `2016-enough-of-hockey-nightmare-in-canada-huffington-post-5-may`,
    year: `2016`,
    bodyHtml: `Enough of Hockey Nightmare in Canada, Huffington Post (5 May 2016)`,
    links: [{ label: `Link`, href: `http://www.huttingtonpost.ca/henry-mintzberg/hockey-nightmare-canada_b_9840552.html` }],
  },
  {
    slug: `2016-lets-not-try-to-fix-health-care-in-quebec-by-breaking-it-m`,
    year: `2016`,
    bodyHtml: `Let's Not Try to Fix Health Care in Quebec by Breaking it, Montreal Gazette (26 February 2016)`,
    links: [{ label: `Link`, href: `https://montrealgazette.com/opinion/columnists/opinion-lets-not-fix-health-care-in-quebec-by-breaking-it` }],
  },
  {
    slug: `2016-ne-rformons-pas-le-systme-de-sant-en-le-mettant-en-pices`,
    year: `2016`,
    bodyHtml: `Ne Réformons Pas le Système de Santé en le Mettant en Pièces, Le Devoir (24 March 2016)`,
    links: [{ label: `Link`, href: `https://www.ledevoir.com/opinion/idees/463756/ne-reformons-pas-le-systeme-de-sante-en-le-mettant-en-pieces` }],
  },
  {
    slug: `2016-canada-welcomes-the-return-of-liberal-democracy-huffington`,
    year: `2016`,
    bodyHtml: `Canada Welcomes The Return of Liberal Democracy, Huffington Post  (15 January 2016)`,
    links: [{ label: `Link`, href: `http://www.huffingtonpost.ca/henry-mintzberg/liberal-democracy-canada_b_8962728.html` }],
  },
  {
    slug: `2016-du-pareil-au-meme-23-september-2016-huffington-post`,
    year: `2016`,
    bodyHtml: `Du Pareil au Meme (23 September 2016), Huffington Post`,
    links: [{ label: `Link`, href: `https://www.huffpost.com/archive/qc/entry/du-pareil-au-meme_b_12154488` }],
  },
  {
    slug: `2016-are-american-voters-trumped-both-ways-15-september-2016`,
    year: `2016`,
    bodyHtml: `Are American Voters Trumped Both Ways? (15 September 2016), Huffington Post`,
    links: [{ label: `Link`, href: `https://www.huffpost.com/archive/ca/entry/are-american-voters-trumped-both-ways_b_12029028` }],
  },
  {
    slug: `2015-we-must-get-past-quebecs-real-scandal-16-november-2015-t`,
    year: `2015`,
    bodyHtml: `We Must Get Past Quebec's Real Scandal (16 November 2015), The Globe and Mail`,
    links: [],
  },
  {
    slug: `2015-how-a-few-spoiler-seats-could-topple-the-conservatives-th`,
    year: `2015`,
    bodyHtml: `How a Few 'Spoiler' Seats Could Topple the Conservatives, The Globe and Mail (26 August 2015)`,
    links: [{ label: `Link`, href: `http://www.theglobeandmail.com/globe-debate/how-a-few-spoiler-seats-could-topple-the-tories/article26115657/` }],
  },
  {
    slug: `2015-we-still-need-to-talk-about-the-globes-bizarre-endorsement`,
    year: `2015`,
    bodyHtml: `We Still Need to Talk About the Globe's Bizarre Endorsement, Huffington Post (9 November 2015)`,
    links: [{ label: `Link`, href: `http://www.huffingtonpost.ca/henry-mintzberg/globe-endorsement_b_8362406.html` }],
  },
  {
    slug: `2015-dont-call-it-a-scandal-volkswagen-corruption-is-a-syndrome`,
    year: `2015`,
    bodyHtml: `Don't Call it a Scandal: Volkswagen Corruption is a Syndrome, Globe & Mail (23 September 2015)`,
    links: [{ label: `Link`, href: `https://www.facebook.com/theglobeandmail/posts/10153556106008904` }],
  },
  {
    slug: `2015-weve-lost-control-of-our-own-game-with-karl-moore-the-gl`,
    year: `2015`,
    bodyHtml: `We've Lost Control of our own Game (with Karl Moore), The Globe and Mail (4 June 2015)`,
    links: [{ label: `Link`, href: `http://www.theglobeandmail.com/globe-debate/weve-lost-control-of-our-own-game/article24812393/` }],
  },
  {
    slug: `2014-the-end-of-thinking-huffington-post-11-july-2014`,
    year: `2014`,
    bodyHtml: `The End of Thinking?, Huffington Post (11 July 2014)`,
    links: [{ label: `Link`, href: `https://www.huffpost.com/entry/the-end-of-thinking_b_5575017` }],
  },
  {
    slug: `2014-the-fall-of-the-berlin-walla-triumph-for-capitalism-cnbc`,
    year: `2014`,
    bodyHtml: `The Fall of the Berlin Wall—a triumph for capitalism?, CNBC.com`,
    links: [{ label: `Link`, href: `http://www.cnbc.com/id/102165846` }],
  },
  {
    slug: `2014-le-prof-mintzberg-persiste-et-signe-les-affaires-27-februa`,
    year: `2014`,
    bodyHtml: `Le Prof Mintzberg persiste et signe, Les Affaires (27 February 2014)`,
    links: [{ label: `Link`, href: `https://www.mcgill.ca/desautels/files/desautels/channels/attach/les_affaires_mintzberg_march2014.pdf` }],
  },
  {
    slug: `2014-think-less-learn-more-iese-insight-2014`,
    year: `2014`,
    bodyHtml: `Think Less, Learn More, IESE Insight (2014)`,
    links: [{ label: `Link`, href: `http://www.ieseinsight.com/fichaMaterial.aspx` }],
  },
  {
    slug: `2014-the-end-of-thinking-huffington-post-11-july-2014-1`,
    year: `2014`,
    bodyHtml: `The End of Thinking?, Huffington Post (11 July 2014)`,
    links: [{ label: `Link`, href: `http://www.huffingtonpost.com/henry-mintzberg/the-end-of-thinking_b_5575017.html` }],
  },
  {
    slug: `2012-its-time-to-rebalance-our-sectors-and-society-the-guardian`,
    year: `2012`,
    bodyHtml: `It’s Time to Rebalance Our Sectors and Society, The Guardian (2012)`,
    links: [{ label: `Link`, href: `http://www.theguardian.com/sustainable-business/blog/government-corporations-rebalance-sector-society` }],
  },
  {
    slug: `2012-quand-les-gourous-ne-savent-plus-a-quel-saint-se-vouer-29-m`,
    year: `2012`,
    bodyHtml: `Quand les Gourous Ne Savent Plus a Quel Saint se Vouer (29 May 2012), L'Express`,
    links: [],
  },
  {
    slug: `2012-the-antimba-21-may-2012-the-new-york-times`,
    year: `2012`,
    bodyHtml: `The Anti-MBA (21 May 2012), The New York Times`,
    links: [],
  },
  {
    slug: `2012-an-appeal-to-reason-to-quebecs-selfabsorbed-students-the`,
    year: `2012`,
    bodyHtml: `An Appeal to Reason to Quebec\`s Self-absorbed Students, The Globe and Mail (1 May 2012)`,
    links: [{ label: `Link`, href: `http://www.theglobeandmail.com/globe-debate/an-appeal-to-reason-to-quebecs-self-absorbed-students/article4106827/` }],
  },
  {
    slug: `2012-charest-is-no-putin-poutine-maybe-huffington-post-12-jun`,
    year: `2012`,
    bodyHtml: `Charest is no Putin. Poutine, Maybe, Huffington Post (12 June 2012)`,
    links: [{ label: `Link`, href: `http://www.huffingtonpost.ca/henry-mintzberg/quebec-protests_b_1581054.html` }],
  },
  {
    slug: `2011-who-will-fix-the-us-economy-see-project-syndicate-2011-ww`,
    year: `2011`,
    bodyHtml: `Who Will Fix the US Economy? See Project Syndicate, 2011 (www.project-syndicate.org)`,
    links: [{ label: `www.project-syndicate.org`, href: `http://www.project-syndicate.org/` }, { label: `Link`, href: `http://www.project-syndicate.org/` }],
  },
  {
    slug: `2011-conserving-canada-or-a-conservative-canada-globe-and-mail`,
    year: `2011`,
    bodyHtml: `Conserving Canada or a Conservative Canada?, Globe and Mail (31 March 2011)`,
    links: [{ label: `Link`, href: `http://www.theglobeandmail.com/news/opinions/opinion/conserving-canada-or-a-conservative-canada/article1963952/singlepage/` }],
  },
  {
    slug: `2011-two-strikes-against-diplomacy-huffington-post-17-february`,
    year: `2011`,
    bodyHtml: `Two Strikes Against Diplomacy, Huffington Post (17 February 2011)`,
    links: [{ label: `Link`, href: `https://www.mcgill.ca/newsroom/channels/news/huffington-post-two-strikes-against-diplomacy-172000` }],
  },
  {
    slug: `2010-getting-the-government-we-deserve-huffington-post-november`,
    year: `2010`,
    bodyHtml: `Getting the Government we Deserve, Huffington Post (November 2010)`,
    links: [{ label: `Link`, href: `http://www.huffingtonpost.com/henry-mintzberg/getting-the-government-we_1_b_784781.html` }],
  },
  {
    slug: `2010-the-problem-is-enterprise-not-economics-huffington-post-7`,
    year: `2010`,
    bodyHtml: `The Problem Is Enterprise, Not Economics, Huffington Post (7 July 2010)`,
    links: [{ label: `Link`, href: `http://www.huffingtonpost.com/henry-mintzberg/the-problem-is-enterprise_b_636852.html` }],
  },
  {
    slug: `2010-henry-mintzberg-on-how-the-enterprises-trashed-the-economy`,
    year: `2010`,
    bodyHtml: `Henry Mintzberg on How the Enterprises Trashed the Economy, The Economist (December 2010)`,
    links: [{ label: `Link`, href: `http://www.economist.com/blogs/freeexchange/2010/12/management` }],
  },
  {
    slug: `2010-time-for-america-to-befriend-israel-huffington-post-7-apri`,
    year: `2010`,
    bodyHtml: `Time for America to Befriend Israel, Huffington Post (7 April 2010)`,
    links: [{ label: `Link`, href: `http://www.huffingtonpost.com/henry-mintzberg/time-for-america-to-befri_b_528437.html` }],
  },
  {
    slug: `2010-management-education-on-the-fly-8-march-2010-bloomberg-bu`,
    year: `2010`,
    bodyHtml: `Management Education on the Fly (8 March 2010), Bloomberg Businessweek`,
    links: [],
  },
  {
    slug: `2009-no-more-executive-bonuses-wall-street-journal-30-november`,
    year: `2009`,
    bodyHtml: `No More Executive Bonuses!, Wall Street Journal (30 November 2009)`,
    links: [{ label: `Link`, href: `https://www.wsj.com/articles/SB10001424052970203922804578080670062571256` }],
  },
  {
    slug: `2009-were-overled-and-undermanaged-business-week-17-august-200`,
    year: `2009`,
    bodyHtml: `We're Overled and Undermanaged, Business Week (17 August 2009)—reversing what is commonly thought to be that problem in American business today`,
    links: [],
  },
  {
    slug: `2009-the-best-leadership-is-good-management-bloomberg-businesswe`,
    year: `2009`,
    bodyHtml: `The Best Leadership Is Good Management, Bloomberg Businessweek (6 August 2009)`,
    links: [{ label: `Link`, href: `https://www.bloomberg.com/news/articles/2009-08-06/the-best-leadership-is-good-management` }],
  },
  {
    slug: `2009-what-managers-really-do-wall-street-journal-17-august-2009`,
    year: `2009`,
    bodyHtml: `What Managers Really Do, Wall Street Journal (17 August 2009)`,
    links: [{ label: `Download`, href: `sites/default/files/article/download/mgrsreallydo.pdf` }],
  },
  {
    slug: `2009-its-time-to-call-the-bluff-of-those-highrolling-ceos-the-g`,
    year: `2009`,
    bodyHtml: `It’s Time to Call the Bluff of those Highrolling CEOS, The Globe and Mail (3 April 2009)`,
    links: [{ label: `Link`, href: `https://www.theglobeandmail.com/opinion/its-time-to-call-the-bluff-of-those-highrolling-ceos/article783740/` }],
  },
  {
    slug: `2009-debate-about-us-management-education-and-the-economic-cris`,
    year: `2009`,
    bodyHtml: `Debate About U.S. Management Education and the Economic Crises, Harvard Business Idea Cast (March 2009)`,
    links: [],
  },
  {
    slug: `2009-americas-monumental-failure-of-management-the-globe-and-ma`,
    year: `2009`,
    bodyHtml: `America’s Monumental Failure of Management, The Globe and Mail (16 March 2009)`,
    links: [{ label: `Link`, href: `https://www.theglobeandmail.com/opinion/americas-monumental-failure-of-management/article1149860/` }],
  },
  {
    slug: `2008-le-dclin-de-la-gestion-amricaine-la-presse-21-july-2008`,
    year: `2008`,
    bodyHtml: `Le Déclin de la Gestion Américaine, La Presse (21 July 2008)`,
    links: [],
  },
  {
    slug: `2008-a-topdown-problem-the-globe-and-mail-18-july-2008`,
    year: `2008`,
    bodyHtml: `A Top-Down Problem, The Globe and Mail (18 July 2008)`,
    links: [{ label: `Link`, href: `http://www.theglobeandmail.com/globe-debate/a-top-down-problem/article1057775/` }],
  },
  {
    slug: `2008-managing-our-way-out-of-this-mess-the-globe-and-mail-4-dec`,
    year: `2008`,
    bodyHtml: `Managing Our Way Out of this Mess, The Globe and Mail (4 December 2008)`,
    links: [{ label: `Link`, href: `http://www.theglobeandmail.com/globe-debate/managing-our-way-out-of-this-mess/article717151/` }],
  },
  {
    slug: `2008-we-must-get-past-quebecs-real-scandal-the-globe-and-mail`,
    year: `2008`,
    bodyHtml: `We Must Get Past Quebec’s Real Scandal, The Globe and Mail (16 November 2008)`,
    links: [{ label: `Link`, href: `http://www.theglobeandmail.com/globe-debate/we-must-get-past-quebecs-real-scandal/article740165/` }],
  },
  {
    slug: `2008-americas-scorched-earth-management-project-syndicate-appe`,
    year: `2008`,
    bodyHtml: `America’s Scorched Earth Management, Project Syndicate (appeared in many newspapers around the world (July 2008)`,
    links: [{ label: `Link`, href: `http://www.project-syndicate.org/commentary/america-s-scorched-earth-management` }],
  },
  {
    slug: `2007-le-qubec-entre-deux-manifestes-with-antonia-maioni-le-de`,
    year: `2007`,
    bodyHtml: `Le Québec entre Deux Manifestes (with Antonia Maioni), Le Devoir (16 April 2007)`,
    links: [],
  },
  {
    slug: `2007-between-two-manifestos-with-antonia-maioni-submitted-for-p`,
    year: `2007`,
    bodyHtml: `Between Two Manifestos (with Antonia Maioni, submitted for publication)—about the future for economic development in Quebec.`,
    links: [],
  },
  {
    slug: `2006-pandering-to-gun-alcohol-and-cellphone-users-is-killing-us`,
    year: `2006`,
    bodyHtml: `Pandering to Gun, Alcohol, and Cellphone Users is Killing Us (Web exclusive comment, Globe and Mail, 20 September 2006)`,
    links: [],
  },
  {
    slug: `2006-global-or-worldly-with-karl-moore-world-business-april`,
    year: `2006`,
    bodyHtml: `Global or Worldly? (with Karl Moore), World Business (April, 2006)—we favor worldly`,
    links: [{ label: `Link`, href: `http://www.managementtoday.co.uk/news/547318/Global-worldly/` }],
  },
  {
    slug: `2006-communityship-is-the-answer-financial-times-23-october-200`,
    year: `2006`,
    bodyHtml: `Communityship is the Answer, Financial Times (23 October 2006)`,
    links: [{ label: `Link`, href: `https://conversational-leadership.net/quotation/communityship-is-the-answer/` }],
  },
  {
    slug: `2006-the-leadership-debate-with-henry-mintzberg-communityship-i`,
    year: `2006`,
    bodyHtml: `The Leadership Debate with Henry Mintzberg: Community-ship is the answer, The Leadership Debate, Financial Times`,
    links: [],
  },
  {
    slug: `2006-how-productivity-killed-american-enterprise-written-in-2006`,
    year: `2006`,
    bodyHtml: `How Productivity Killed American Enterprise (Written in 2006)`,
    links: [{ label: `Download`, href: `sites/default/files/article/download/productivity2008.pdf` }],
  },
  {
    slug: `2004-extremism-in-the-defense-of-liberty-is-no-use-the-globe-and`,
    year: `2004`,
    bodyHtml: `Extremism in the Defense of Liberty is No Use, The Globe and Mail (27 August 2004)`,
    links: [],
  },
  {
    slug: `2004-last-thought-on-the-olympicsa-sort-of-canadian-triumph-th`,
    year: `2004`,
    bodyHtml: `Last Thought on the Olympics…a Sort of Canadian Triumph?, The Globe and Mail (9 September 2004)`,
    links: [],
  },
  {
    slug: `2003-africas-best-practices-kazakhstan-monitor-november-2003`,
    year: `2003`,
    bodyHtml: `Africa’s “Best Practices”, Kazakhstan Monitor (November 2003); Bangkok Post (October 29, 2003); Daily Times of Pakistan (March 9,2004)`,
    links: [{ label: `Link`, href: `http://archives.dailytimes.com.pk/business/04-Nov-2003/comment-africa-s-best-practices` }],
  },
  {
    slug: `2003-marching-off-to-postwar-the-globe-and-mail-april-29-2003`,
    year: `2003`,
    bodyHtml: `Marching Off to Postwar, The Globe and Mail (April 29, 2003)`,
    links: [],
  },
  {
    slug: `2003-but-mr-bush-why-now-the-globe-and-mail-february-20-200`,
    year: `2003`,
    bodyHtml: `But Mr. Bush, Why now?, The Globe and Mail (February 20, 2003)`,
    links: [{ label: `Link`, href: `http://www.theglobeandmail.com/globe-debate/but-mr-bush-why-now/article748911/` }],
  },
  {
    slug: `2002-the-privilege-of-medicare-the-globe-and-mail-october-22-2`,
    year: `2002`,
    bodyHtml: `The Privilege of Medicare, The Globe and Mail (October 22, 2002)`,
    links: [{ label: `Link`, href: `https://www.theglobeandmail.com/opinion/the-privilege-of-medicare/article757308/` }],
  },
  {
    slug: `2002-productivity-is-a-time-bomb-the-globe-and-mail-13-june-200`,
    year: `2002`,
    bodyHtml: `Productivity is a Time Bomb, The Globe and Mail (13 June 2002)`,
    links: [],
  },
  {
    slug: `2001-do-mbas-make-better-ceos-fortune-magazine-2001`,
    year: `2001`,
    bodyHtml: `"Do MBAs Make Better CEOs?", Fortune Magazine (2001)`,
    links: [{ label: `Link`, href: `https://money.cnn.com/magazines/fortune/fortune_archive/2001/02/19/296894/index.htm` }],
  },
  {
    slug: `1999-theres-no-compensation-for-hypocrisy-financial-times-octo`,
    year: `1999`,
    bodyHtml: `There's No Compensation for Hypocrisy, Financial Times (October 29, 1999)`,
    links: [],
  },
  {
    slug: `1998-softly-softly-over-blood-and-thunder-financial-times-octo`,
    year: `1998`,
    bodyHtml: `Softly, Softly over Blood and Thunder, Financial Times (October 1998)`,
    links: [],
  },
  {
    slug: `1998-greedy-workers-mimic-managers-globe-and-mail-october-1998`,
    year: `1998`,
    bodyHtml: `Greedy Workers Mimic Managers, Globe and Mail (October 1998)`,
    links: [],
  },
  {
    slug: `1998-the-time-is-right-montreal-gazette-march-17-1998`,
    year: `1998`,
    bodyHtml: `The Time is Right, Montreal Gazette (March 17, 1998)`,
    links: [],
  },
  {
    slug: `1997-the-campaign-begins-today-globe-and-mail-june-24-1997`,
    year: `1997`,
    bodyHtml: `The Campaign Begins Today, Globe and Mail (June 24, 1997)`,
    links: [],
  },
  {
    slug: `1997-o-canada-who-will-stand-on-guard-for-thee-globe-and-mail`,
    year: `1997`,
    bodyHtml: `O Canada, Who Will Stand on Guard for Thee?, Globe and Mail (February 10, 1997)`,
    links: [],
  },
  {
    slug: `1996-chief-electoral-officers-logic-shows-dangers-of-nationalism`,
    year: `1996`,
    bodyHtml: `Chief Electoral Officer's Logic shows dangers of Nationalism, Montreal Gazette (July 30, 1996)`,
    links: [],
  },
  {
    slug: `1996-readers-should-have-larger-say-in-running-newspapers-montre`,
    year: `1996`,
    bodyHtml: `Readers Should Have Larger Say in Running Newspapers, Montreal Gazette (August 3, 1996)`,
    links: [],
  },
  {
    slug: `1996-federalists-show-some-backbone-globe-and-mail-october-5`,
    year: `1996`,
    bodyHtml: `Federalists, Show Some Backbone, Globe and Mail (October 5, 1996)`,
    links: [],
  },
  {
    slug: `1996-beyond-the-mba-harvey-schacter-october-1996`,
    year: `1996`,
    bodyHtml: `Beyond the MBA (Harvey Schacter) October 1996`,
    links: [],
  },
  {
    slug: `1996-the-yes-and-the-yes-published-in-canadian-newspapers-in`,
    year: `1996`,
    bodyHtml: `The 'Yes' and the 'Yes,' published in Canadian newspapers in English and French (1996)`,
    links: [],
  },
  {
    slug: `1996-decentralization-means-centralization-published-in-canadian`,
    year: `1996`,
    bodyHtml: `Decentralization Means Centralization, published in Canadian newspapers in English and French (1996)`,
    links: [],
  },
  {
    slug: `1995-its-time-federalists-challenge-myths-that-sovereignists-emp`,
    year: `1995`,
    bodyHtml: `It’s Time Federalists Challenge Myths that Sovereignists Employ, Montreal Gazette (November 1995)`,
    links: [],
  },
  {
    slug: `1995-tat-de-droit-et-capitalisme-sauvage-la-tribune-paris-1`,
    year: `1995`,
    bodyHtml: `État de Droit et Capitalisme Sauvage, La Tribune (Paris), (17 février 1995)`,
    links: [],
  },
  {
    slug: `1989-le-management-victime-des-business-schools-le-monde-nov`,
    year: `1989`,
    bodyHtml: `Le Management: Victime des "Business Schools", Le Monde (November 1989)`,
    links: [{ label: `Link`, href: `http://www.lemonde.fr/cgi-bin/ACHATS/acheter.cgi` }],
  },
  {
    slug: `1989-tenure-itself-threatens-freedom-of-expression-mcgill-report`,
    year: `1989`,
    bodyHtml: `Tenure Itself Threatens Freedom of Expression, McGill Reporter (March 15, 1989)`,
    links: [],
  },
]
